apiVersion: v1
kind: Service
metadata:
  name: data-collector
  labels:
    app: data-collector
spec:
  type: ClusterIP
  selector:
    app: data-collector
  ports:
  - port: 5001
    targetPort: 5001
    protocol: TCP