apiVersion: v1
kind: Service
metadata:
  name: fan-controller
  labels:
    app: fan-controller
spec:
  type: ClusterIP
  selector:
    app: fan-controller
  ports:
  - port: 5004
    targetPort: 5004
    protocol: TCP