apiVersion: v1
kind: Service
metadata:
  name: green-meter
  labels:
    app: green-meter
spec:
  type: ClusterIP
  selector:
    app: green-meter
  ports:
  - port: 5006
    targetPort: 5006
    protocol: TCP