apiVersion: v1
kind: Service
metadata:
  name: ml-controller
  labels:
    app: ml-controller
spec:
  type: ClusterIP
  selector:
    app: ml-controller
  ports:
  - port: 5003
    targetPort: 5003
    protocol: TCP