apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-controller
  labels:
    app: ml-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-controller
  template:
    metadata:
      labels:
        app: ml-controller
    spec:
      containers:
      - name: ml-controller
        image: ali264/green-cloud-ml-controller:latest
        ports:
        - containerPort: 5003
        env:
        - name: RUN_MODE
          value: "docker"