apiVersion: v1
kind: Service
metadata:
  name: sensor-visualizer
  labels:
    app: sensor-visualizer
spec:
  type: ClusterIP
  selector:
    app: sensor-visualizer
  ports:
  - port: 5002
    targetPort: 5002
    protocol: TCP