apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-tester
  labels:
    app: workload-tester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-tester
  template:
    metadata:
      labels:
        app: workload-tester
    spec:
      containers:
      - name: workload-tester
        image: ali264/green-cloud-workload-tester:latest
        ports:
        - containerPort: 5005
        env:
        - name: RUN_MODE
          value: "docker"